version: '3.8'

services:
  backend:
    build: ./backend
    container_name: ghost-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: ghost-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0

  redis:
    image: redis/redis-stack:latest
    container_name: ghost-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  ghost-ingester:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ghost-ingester
    depends_on:
      - redis
    env_file:
      - .env
    command: python ingester.py
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M

volumes:
  redis_data:
  node_modules:




# version: '3.8'

# services:
#   backend:
#     build: ./backend
#     container_name: ghost-backend
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./backend:/app
#     depends_on:
#       - redis
#     command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

#   frontend:
#     build: ./frontend
#     container_name: ghost-frontend
#     ports:
#       - "5173:5173"
#     volumes:
#       - ./frontend:/app
#       - /app/node_modules
#     depends_on:
#       - backend
#     command: npm run dev -- --host 0.0.0.0

#   redis:
#     image: redis/redis-stack:latest
#     container_name: ghost-redis
#     ports:
#       - "6379:6379"
  

  # ingester:
  #   build: ./backend
  #   container_name: ghost-ingester
  #   depends_on:
  #     - redis
  #   env_file:
  #     - .env
  #   command: python ingester.py
  #   # ✅ FIX: Add a memory limit and restart policy to prevent OOM errors
  #   restart: unless-stopped
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 1024M